import { brandPrimary, functionalColors, neutralGray } from "./colors";

export const statisticTokens = {
  "statistic-title-color": "rgba(0,0,0,0.45)",
  "statistic-title-font-size": "14px",
  "statistic-title-line-height": "22px",
  "statistic-value-color": "rgba(0,0,0,0.88)",
  "statistic-value-font-size": "24px",
  "statistic-value-font-weight": "600",
  "statistic-value-line-height": "32px",
  "statistic-prefix-font-size": "20px",
  "statistic-suffix-font-size": "14px",
  "statistic-suffix-color": "rgba(0,0,0,0.65)",
  "statistic-trend-up": functionalColors.success,
  "statistic-trend-down": functionalColors.danger,
  "statistic-trend-font-size": "12px",
  "statistic-trend-line-height": "20px",
  "statistic-loading-bg": neutralGray[3],
  "statistic-loading-highlight": neutralGray[4],
  "statistic-group-gap": "24px",
  "statistic-group-gap-sm": "16px",
  "statistic-primary": brandPrimary[6],
  "statistic-card-height": "120px",
  "statistic-card-padding": "20px",
  "statistic-card-radius": "12px",
  "statistic-card-bg": neutralGray[1],
  "statistic-card-border-color": neutralGray[4],
  "statistic-card-shadow": "none",
  "statistic-card-icon-bg-primary": "rgba(22, 93, 255, 0.08)",
  "statistic-card-icon-bg-success": "rgba(0, 180, 42, 0.08)",
  "statistic-card-icon-bg-warning": "rgba(255, 125, 0, 0.08)",
  "statistic-card-icon-bg-danger": "rgba(245, 63, 63, 0.08)",
  "statistic-card-hover-shadow": "0 4px 12px rgba(0, 0, 0, 0.08)",
  "statistic-card-description-color": "rgba(0,0,0,0.45)",
  "statistic-card-description-font-size": "12px",
  "statistic-card-description-line-height": "20px",
  "statistic-card-icon-size": "22px",
} as const;

export type StatisticTokenKey = keyof typeof statisticTokens;

export const statisticUsageTokenNames = [
  "statistic-title-color",
  "statistic-value-color",
  "statistic-value-font-size",
  "statistic-trend-up",
  "statistic-trend-down",
  "statistic-group-gap",
  "statistic-card-padding",
  "statistic-card-radius",
  "statistic-card-shadow",
  "statistic-card-hover-shadow",
  "statistic-card-bg",
] as const;
