export {
  Empty,
  EMPTY_GALLERY_TYPES,
  EMPTY_TYPE_ILLUSTRATIONS,
  EMPTY_TYPE_PRESETS,
  CommunicationEmptyIllustration,
  DefaultEmptyIllustration,
  DeviceEmptyIllustration,
  DocumentEmptyIllustration,
  ErrorEmptyIllustration,
  FilterEmptyIllustration,
  FolderEmptyIllustration,
  InspectionEmptyIllustration,
  NetworkEmptyIllustration,
  OfflineEmptyIllustration,
  PermissionEmptyIllustration,
  RectificationEmptyIllustration,
  RiskEmptyIllustration,
  SearchEmptyIllustration,
  StoreEmptyIllustration,
  TaskEmptyIllustration,
  type EmptyPreset,
  type EmptyProps,
  type EmptyType,
} from "./empty/index";
